services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - compliance-network

  compliance-app:
    build: .
    container_name: compliance-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - compliance-network
    volumes:
      - ./playbooks:/app/linux-compliance-scanner

  ansible-exec:
    image: ansible_ee:latest
    container_name: ansible-exec
    restart: unless-stopped
    networks:
      - compliance-network
    volumes:
      - ./ansible/playbooks:/runner/project/playbooks:ro
      - ./ansible/playbooks/vault_pass.txt:/runner/secrets/vault_pass.txt:ro

volumes:
  postgres_data:

networks:
  compliance-network:
    driver: bridge

